Artificial-Intelligence-HSBI-TDU/KI-Vorlesung

- data/schedule.yaml
schließe den inhalt von `data/schedule.yaml` wieder in `---` ein. scheint auch ohne zu funktionieren, aber typischerweise haben yaml-dateien diesen beginn/dieses ende ...
> add '---' to schedule.yaml

- markdown/misc/grading/_index.md
- markdown/misc/grading/grading-fhb/index.md
- markdown/misc/grading/grading-tdu/index.md
> Orga: Split Grading

- markdown/assignments/sheet01/index.md
Um die Abgabe leichter zu machen (die Studis sollen ja angeben, welche Aufgaben sie gelöst haben), werden Nummern eingeführt: "Ax.y", wobei "x" das Blatt ist und "y" die Aufgabennummer.
> Führe Aufgabennummern ein für die Abgabe

- markdown/_index.md
> Stundenplan FHB

- markdown/intro/intro-ai/index.md
- markdown/intro/problems/index.md
Aktualisiere Videos für die KI-Einführung und für Problemlösen
> Update Links KI-Einführung

- markdown/ml/ml1_perceptron/index.md
@cyildiz Dies ist der Ersatz für #104 (Fix für Attachments im `master` eingespielt und `ml1`-Branch rebased). 
Bitte arbeite auf diesem Branch/PR weiter. Den #104 kannst Du dann schließen (ohne Mergen).
> ML1 rebased

- markdown/assignments/sheet06/index.md
> first draft of sheet 6

- markdown/ml/ml1_perceptron/index.md
- markdown/ml/ml1_perceptron/outcomes.md
> nn1 - learning outcomes

- markdown/ml/ml1_perceptron/index.md
- markdown/ml/ml1_perceptron/outcomes.md
- markdown/ml/ml2_linear_regression/index.md
- markdown/ml/ml2_linear_regression/outcomes.md
> nn2-outcomes

- data/schedule.yaml
- Heine Sprechstunde in KW52 
- NN7 für alle in KW01
- NN8 in KW02 (nur FHB)
- B10 in KW02 (nur FHB)
@cyildiz Hab ich noch was vergessen?
> Update Planung: keine Sprechstunde in KW52

- markdown/assignments/sheet06/index.md
> fix rendering of sqrt

- config.yaml
- markdown/org/exam/exam-fhb.md
> [VL]: Exams

- markdown/assignments/sheet01.md
- markdown/csp/ac3.md
- markdown/csp/backtrackingsearch.md
- markdown/ea/intro.md
- markdown/games/alphabeta.md
- markdown/games/heuristics.md
- markdown/games/intro.md
- markdown/intro/intro-ai.md
- markdown/org/syllabus.md
- markdown/org/teaser.md
- markdown/search/local/annealing.md
- markdown/search/local/gradient.md
> [ORG] Zitate und Fremdmaterial prüfen: TULLU-Regel

- .github/actions/alpine-pandoc-hugo/Dockerfile
- .github/actions/alpine-pandoc-hugo/install-packages.sh
> [TOOLING] Update Docker 

- markdown/csp/ac3.md
- markdown/csp/heuristics.md
- markdown/csp/intro.md
- markdown/dtl/cal2.md
- markdown/dtl/cal3.md
- markdown/dtl/entropy.md
- markdown/dtl/mlbasics.md
- markdown/dtl/pruning.md
- markdown/ea/ga.md
- markdown/games/alphabeta.md
- markdown/games/minimax.md
- markdown/intro/intro-ai.md
- markdown/intro/problems.md
- markdown/naivebayes/nb.md
- markdown/naivebayes/probability.md
- markdown/nn/nn1_perceptron.md
- markdown/nn/nn2_linear_regression.md
- markdown/nn/nn3_logistic_regression.md
- markdown/nn/nn4_overfitting.md
- markdown/nn/nn5_mlp.md
- markdown/nn/nn6_backprop.md
- markdown/nn/nn7_training_testing.md
- markdown/nn/nn8_testing.md
- markdown/search/informed/astar.md
- markdown/search/informed/bestfirst.md
- markdown/search/informed/branchandbound.md
- markdown/search/local/annealing.md
- markdown/search/local/gradient.md
- markdown/search/uninformed/bfs.md
- markdown/search/uninformed/dfs.md
> [VL] Add new quizzes in open course

- markdown/assignments/sheet01.md
- markdown/assignments/sheet06.md
the shortcode `challenges` would simply wrap it's content into a div w/ class 'challenge', so we can just use a markdown div w/ class 'challenge' and forget about this hugo shortcode :)
> Challenges: Replace hugo shortcode 'challenges' w/ plain markdown div w/ class 'challenges'

- markdown/org/grading-tdu.md
Noten & Credits für TDU
fixes #179
> [ORGA] Grading für TDU anpassen

- markdown/_index.md
> [ORGA] Link auf Moodle-Kursraum einpflegen

- data/schedule.yaml
- markdown/_index.md
- markdown/org/faq.md
* Landing-Page: Link auf Moodle-Kurs für TDU-Studis (für die Brücke zum ILIAS)
* Schedule: Zeiten für Gruppenbeitritt
* FAQ: Erläuterung des Verfahrens und Angabe der Zeiten für Gruppenbeitritt
* Landing-Page: Keine Zeitverschiebung für G3
* FAQ: Hinweis zur Zeitverschiebung
> [ORGA] Hinweise zur Gruppen und Beitritt zu Breakout-Gruppen

- markdown/assignments/sheet01.md
Aufgaben für Meilenstein 1: Problemlösen, Suche
> [ASSIGNMENT] Aufgaben für Meilenstein 1.1

- markdown/assignments/sheet02.md
Aufgaben für Meilenstein 2: Lokale Suche, GA
> [ASSIGNMENT] Aufgaben für Meilenstein 1.2

- markdown/assignments/sheet03.md
Aufgaben für Meilenstein 3: Constraints
> [ASSIGNMENT] Aufgaben für Meilenstein 1.3

- markdown/assignments/sheet04.md
Aufgaben für Meilenstein 4: Entscheidungsbäume
> [ASSIGNMENT] Aufgaben für Meilenstein 1.4

- markdown/assignments/poster1.md
- markdown/assignments/sheet01.md
- markdown/assignments/sheet02.md
- markdown/assignments/sheet03.md
- markdown/assignments/sheet04.md
Füge einen Hinweis zur Zuverlässigkeit des AIMA-Python-Codes hinzu.
Der Java-Code scheint zu funktionieren, im Python-Code haben die Studis dieses Jahr einige Fehler und "TODO"-Marker gefunden?!
> [ASSIGNMENT] B01..B04, P1: add note regarding todo markers in AIMA-Python

- markdown/_index.md
Hallo Carsten,
Finn und ich haben die DigikoS Infos ergänzt. Passt das so für dich?
Viele Grüße
Henrik
> [ORG] Füge Info zu Unterstützung durch DigikoS ein

- README.md
- markdown/_index.md
- entferne Logo in `_index.md`
- füge engl. Absatz in `README.md` ein (mit Logo)
- ergänze Urheberhinweis für Logo
fixes #208
> [ORG] Abbildung zu DigikoS funktioniert noch nicht im gerenderten Skript

- markdown/assignments/poster1.md
> [ASSIGNMENT] Poster 1: Fußnoten und Links interferieren

- README.md
- markdown/_index.md
> [ORG] add url to Digital Mobil project

- markdown/assignments/files/perzeptron_lernalgorithmus_starter.ipynb
- markdown/assignments/sheet05.md
Klassifizierung mit dem Perzeptron Lernalgorithmus.
> Meilenstein 2.1 - Perzeptron

- markdown/org/faq.md
- maximal 11P für TDU (wegen Überschneidung mit Zwischenprüfungen)
- Nachfrist kann von allen genutzt werden (auch wenn vorher fristgerecht abgegeben und vorgestellt wurde). Es wird aber in dem Fall die letzte Abgabe bewertet (keine Punkte für Feedback und Vorstellung).
> Zusätzliche Bemerkungen zu der Nachfrist im faq

- markdown/assignments/sheet07.md
> [ASSIGNMENTS] Sheet07 / M2.3: Overfitting & MLP

- markdown/assignments/files/mlp_starter.ipynb
- markdown/assignments/poster2.md
> [ASSIGNMENT] Poster 2

- markdown/assignments/sheet07.md
Ein paar Korrekturen und Verbessrungen.
> [ASSIGNMENT] M2.3 Korrigiere die Reihenfolge der Textblöcke

- config.yaml
- data/schedule.yaml
- markdown/_index.md
- markdown/logic/_index.md
- markdown/logic/intro.md
- markdown/logic/modelle.md
- markdown/logic/resolution.md
- markdown/logic/syntax.md
- markdown/nn/nn9_llm.md
- Enable print in website
- Reformat schedule (not updated yet!)
- Prepare index (mostly)
- Add stub for new LLM lecture
- Add stub for new Logic lecture
@cyildiz 
fixes #232
> [Org] Prepare W23

- readme.md
improves readability in GH preview
> Tool: replace tabs/tab shortcode with tabs/tab fenced div

- readme.md
TDU Abgabetermine für Übungen eingetragen
> Orga: add ue deadlines (TDU)

- admin/exams-tdu.md
- readme.md
Info zu Prüfung, Übung und Noten an der TDU
> Grading TDU

- lecture/csp/ac3.md
- lecture/searching/informed/astar.md
- lecture/searching/informed/bestfirst.md
- lecture/searching/local/gradient.md
> VL: fix links in challenges and tldr

- readme.md
- Fahrplan:  angepasst.
- Team: Wissentschaftliche Mitarbeiterin hinzugefügt.
- Kursformat: vorübergehend angepasst, Daten werden nach Semesterbeginn bekanntgegeben.
- Prüfungsform: hat sich nicht geändert.
> Orga: fix lab time (TDU)

- lecture/ea/ea2-ga.md
> markdown: replace 'phantom' (workaround gh bug)
